// src/lib/doctors.ts
// Centralized typed dummy data for Doctors.
// NOTE: This file mimics the shape of a future backend API response.
// When the real API is ready, replace `doctors` with a fetch call that
// returns data conforming to the `Doctor` type below — no other file
// should need to change.

export type Availability = "Available Today" | "Available Tomorrow" | "Not Available";

export interface Doctor {
  id: string;
  name: string;
  // FIX: optional slug added so real API-backed doctors (which always
  // have one) can link to /doctor-profile/[slug]. Optional keeps the
  // dummy array below valid without editing every entry.
  slug?: string;
  image: string;
  verified: boolean;
  qualification: string;
  specialization: string;
  experienceYears: number;
  hospital: string;
  city: string;
  consultationFee: number;
  rating: number;
  reviewCount: number;
  availability: Availability;
  nextSlot: string;
}

export const specializations = [
  "All Specializations",
  "General Physician",
  "Orthopedic Surgeon",
  "Gynecologist",
  "Dermatologist",
  "Cardiologist",
  "Pediatrician",
  "Neurologist",
  "Dentist",
  "ENT Specialist",
  "Psychiatrist",
] as const;

export const experienceRanges = [
  "All Experience",
  "0-5 Years",
  "5-10 Years",
  "10+ Years",
] as const;

export const availabilityOptions = [
  "Any Day",
  "Available Today",
  "Available Tomorrow",
] as const;

export const doctors: Doctor[] = [
  {
    id: "doc-001",
    name: "Dr. Priya Sharma",
    image: "https://i.pravatar.cc/300?img=47",
    verified: true,
    qualification: "MBBS, MD - General Medicine",
    specialization: "General Physician",
    experienceYears: 8,
    hospital: "Apollo Hospital",
    city: "Delhi",
    consultationFee: 500,
    rating: 4.8,
    reviewCount: 320,
    availability: "Available Today",
    nextSlot: "11:30 AM",
  },
  {
    id: "doc-002",
    name: "Dr. Rahul Verma",
    image: "https://i.pravatar.cc/300?img=12",
    verified: true,
    qualification: "MBBS, MS - Orthopedics",
    specialization: "Orthopedic Surgeon",
    experienceYears: 10,
    hospital: "Max Hospital",
    city: "Mumbai",
    consultationFee: 700,
    rating: 4.7,
    reviewCount: 280,
    availability: "Available Tomorrow",
    nextSlot: "10:00 AM",
  },
  {
    id: "doc-003",
    name: "Dr. Anjali Mehta",
    image: "https://i.pravatar.cc/300?img=32",
    verified: true,
    qualification: "MBBS, DGO - Gynecology",
    specialization: "Gynecologist",
    experienceYears: 7,
    hospital: "Fortis Hospital",
    city: "Bangalore",
    consultationFee: 600,
    rating: 4.9,
    reviewCount: 450,
    availability: "Available Today",
    nextSlot: "02:30 PM",
  },
  {
    id: "doc-004",
    name: "Dr. Sandeep Nair",
    image: "https://i.pravatar.cc/300?img=13",
    verified: true,
    qualification: "MBBS, MD - Dermatology",
    specialization: "Dermatologist",
    experienceYears: 6,
    hospital: "Manipal Hospital",
    city: "Pune",
    consultationFee: 500,
    rating: 4.6,
    reviewCount: 190,
    availability: "Available Tomorrow",
    nextSlot: "09:30 AM",
  },
  {
    id: "doc-005",
    name: "Dr. Kavita Reddy",
    image: "https://i.pravatar.cc/300?img=45",
    verified: true,
    qualification: "MBBS, DM - Cardiology",
    specialization: "Cardiologist",
    experienceYears: 14,
    hospital: "AIIMS",
    city: "Delhi",
    consultationFee: 1200,
    rating: 4.9,
    reviewCount: 610,
    availability: "Available Today",
    nextSlot: "04:00 PM",
  },
  {
    id: "doc-006",
    name: "Dr. Arjun Kapoor",
    image: "https://i.pravatar.cc/300?img=15",
    verified: false,
    qualification: "MBBS, MD - Pediatrics",
    specialization: "Pediatrician",
    experienceYears: 5,
    hospital: "Rainbow Children's Hospital",
    city: "Hyderabad",
    consultationFee: 450,
    rating: 4.5,
    reviewCount: 130,
    availability: "Available Today",
    nextSlot: "12:15 PM",
  },
  {
    id: "doc-007",
    name: "Dr. Neha Gupta",
    image: "https://i.pravatar.cc/300?img=44",
    verified: true,
    qualification: "MBBS, DM - Neurology",
    specialization: "Neurologist",
    experienceYears: 12,
    hospital: "Fortis Hospital",
    city: "Delhi",
    consultationFee: 1000,
    rating: 4.8,
    reviewCount: 275,
    availability: "Not Available",
    nextSlot: "Mon, 09:00 AM",
  },
  {
    id: "doc-008",
    name: "Dr. Vikram Singh",
    image: "https://i.pravatar.cc/300?img=14",
    verified: true,
    qualification: "BDS, MDS - Dental Surgery",
    specialization: "Dentist",
    experienceYears: 9,
    hospital: "Clove Dental",
    city: "Chandigarh",
    consultationFee: 400,
    rating: 4.6,
    reviewCount: 210,
    availability: "Available Today",
    nextSlot: "05:45 PM",
  },
  {
    id: "doc-009",
    name: "Dr. Meera Iyer",
    image: "https://i.pravatar.cc/300?img=48",
    verified: true,
    qualification: "MBBS, MS - ENT",
    specialization: "ENT Specialist",
    experienceYears: 11,
    hospital: "Apollo Hospital",
    city: "Chennai",
    consultationFee: 550,
    rating: 4.7,
    reviewCount: 198,
    availability: "Available Tomorrow",
    nextSlot: "11:00 AM",
  },
  {
    id: "doc-010",
    name: "Dr. Rohan Malhotra",
    image: "https://i.pravatar.cc/300?img=17",
    verified: true,
    qualification: "MBBS, MD - Psychiatry",
    specialization: "Psychiatrist",
    experienceYears: 8,
    hospital: "NIMHANS",
    city: "Bangalore",
    consultationFee: 800,
    rating: 4.9,
    reviewCount: 340,
    availability: "Available Today",
    nextSlot: "03:15 PM",
  },
  {
    id: "doc-011",
    name: "Dr. Sunita Rao",
    image: "https://i.pravatar.cc/300?img=41",
    verified: true,
    qualification: "MBBS, MD - General Medicine",
    specialization: "General Physician",
    experienceYears: 15,
    hospital: "Kokilaben Hospital",
    city: "Mumbai",
    consultationFee: 650,
    rating: 4.8,
    reviewCount: 500,
    availability: "Available Today",
    nextSlot: "10:45 AM",
  },
  {
    id: "doc-012",
    name: "Dr. Karan Chopra",
    image: "https://i.pravatar.cc/300?img=18",
    verified: false,
    qualification: "MBBS, MS - Orthopedics",
    specialization: "Orthopedic Surgeon",
    experienceYears: 4,
    hospital: "Max Hospital",
    city: "Delhi",
    consultationFee: 550,
    rating: 4.3,
    reviewCount: 88,
    availability: "Available Tomorrow",
    nextSlot: "01:30 PM",
  },
  {
    id: "doc-013",
    name: "Dr. Divya Menon",
    image: "https://i.pravatar.cc/300?img=39",
    verified: true,
    qualification: "MBBS, DGO - Gynecology",
    specialization: "Gynecologist",
    experienceYears: 13,
    hospital: "Cloudnine Hospital",
    city: "Bangalore",
    consultationFee: 750,
    rating: 4.9,
    reviewCount: 410,
    availability: "Available Today",
    nextSlot: "06:00 PM",
  },
  {
    id: "doc-014",
    name: "Dr. Amit Joshi",
    image: "https://i.pravatar.cc/300?img=11",
    verified: true,
    qualification: "MBBS, DM - Cardiology",
    specialization: "Cardiologist",
    experienceYears: 18,
    hospital: "Medanta",
    city: "Gurugram",
    consultationFee: 1500,
    rating: 5.0,
    reviewCount: 720,
    availability: "Not Available",
    nextSlot: "Tue, 10:30 AM",
  },
  {
    id: "doc-015",
    name: "Dr. Pooja Bhatt",
    image: "https://i.pravatar.cc/300?img=36",
    verified: true,
    qualification: "MBBS, MD - Dermatology",
    specialization: "Dermatologist",
    experienceYears: 6,
    hospital: "Skinnovation Clinic",
    city: "Ahmedabad",
    consultationFee: 500,
    rating: 4.5,
    reviewCount: 150,
    availability: "Available Today",
    nextSlot: "02:00 PM",
  },
];
